"""Generate the Grafana lab content from the manifest: alert rules and a dashboard.

Grafana is where a Loki detection actually runs in production, as an alert rule
on a schedule. Both files under ``lab/grafana`` are generated here from the same
rule files the replay engine runs, so the lab cannot drift from what CI proves.
A test regenerates them and fails on any difference.

Every query selects ``{job="agentdetect"}`` exactly as the rule files do. Seed
the lab Loki with ``agentdetect seed`` and each fixture's session shows up under
that selector.
"""

from __future__ import annotations

import json
from typing import Any

import yaml

from agentdetect import sigma
from agentdetect.loki import SIGMA_WINDOW
from agentdetect.manifest import Detection, RuleKind, load

DATASOURCE_UID = "agentdetect-loki"
FOLDER = "agentdetect"

_INTERLEAVE_ID = "agent-loop-interleave"
_INTERLEAVE_THRESHOLD = ">= 2.5"
_DATASOURCE = {"type": "loki", "uid": DATASOURCE_UID}


def _strip_comments(logql: str) -> str:
    lines = [line for line in logql.splitlines() if not line.lstrip().startswith("#")]
    return "\n".join(lines).strip()


def firing_sessions(detection: Detection) -> str:
    """One series per session the detection currently fires on, each with value 1."""
    if detection.logql is not None:
        rule = _strip_comments(detection.logql.read_text(encoding="utf-8"))
        return f"count by (session) (\n{rule}\n)"
    converted = sigma.to_logql(detection.rule.read_text(encoding="utf-8"))
    return f"count by (session) (count_over_time({converted} [{SIGMA_WINDOW}]))"


def _alert_rule(detection: Detection) -> dict[str, Any]:
    return {
        "uid": f"ad-{detection.id}",
        "title": detection.title,
        "condition": "C",
        "data": [
            {
                "refId": "A",
                "queryType": "instant",
                "relativeTimeRange": {"from": 900, "to": 0},
                "datasourceUid": DATASOURCE_UID,
                "model": {
                    "refId": "A",
                    "expr": firing_sessions(detection),
                    "queryType": "instant",
                    "editorMode": "code",
                },
            },
            {
                "refId": "B",
                "datasourceUid": "__expr__",
                "model": {"refId": "B", "type": "reduce", "expression": "A", "reducer": "last"},
            },
            {
                "refId": "C",
                "datasourceUid": "__expr__",
                "model": {
                    "refId": "C",
                    "type": "threshold",
                    "expression": "B",
                    "conditions": [{"evaluator": {"type": "gt", "params": [0]}}],
                },
            },
        ],
        # No matching lines is the healthy state for a detection, not a fault.
        "noDataState": "OK",
        "execErrState": "Error",
        "for": "0s",
        "labels": {"detection": detection.id, "attack": " ".join(detection.attack)},
        "annotations": {"summary": f"{detection.id}, ATT&CK {', '.join(detection.attack)}"},
    }


def alert_rules() -> dict[str, Any]:
    """The alert-rule provisioning document: one Grafana rule per detection."""
    return {
        "apiVersion": 1,
        "groups": [
            {
                "orgId": 1,
                "name": "agentdetect",
                "folder": FOLDER,
                "interval": "10s",
                "rules": [_alert_rule(det) for det in load()],
            }
        ],
    }


def render_alert_rules() -> str:
    header = "# Generated by `agentdetect grafana`. Do not edit; change the rule files.\n"
    return header + yaml.safe_dump(alert_rules(), sort_keys=False, width=100)


def _interleave_cycles() -> str:
    """The interleave rule without its threshold: cycles per session, firing or not."""
    det = next(d for d in load() if d.id == _INTERLEAVE_ID)
    if det.logql is None:
        raise ValueError(f"{_INTERLEAVE_ID} has no LogQL port")
    rule = _strip_comments(det.logql.read_text(encoding="utf-8"))
    if not rule.endswith(_INTERLEAVE_THRESHOLD):
        raise ValueError(f"{det.logql.name} no longer ends with {_INTERLEAVE_THRESHOLD!r}")
    return rule[: -len(_INTERLEAVE_THRESHOLD)].rstrip()


def _session_logs(session: str) -> str:
    return (
        f'{{job="agentdetect"}} | json | session="{session}" '
        "| line_format `{{ .event_type }}  exit={{ .exit_code }}  "
        "{{ .command_line }}{{ .dest_host }}`"
    )


def dashboard() -> dict[str, Any]:
    native = [d for d in load() if d.kind is RuleKind.SPL]
    flagged_targets = [
        {
            "refId": chr(ord("A") + i),
            "datasource": _DATASOURCE,
            "expr": f'label_replace({firing_sessions(det)}, "rule", "{det.id}", "", "")',
            "queryType": "instant",
            "editorMode": "code",
        }
        for i, det in enumerate(native)
    ]
    return {
        "uid": "agentdetect",
        "title": "agentdetect on Loki",
        "tags": ["agentdetect"],
        "schemaVersion": 39,
        "time": {"from": "now-5m", "to": "now"},
        "refresh": "10s",
        "panels": [
            {
                "id": 1,
                "type": "table",
                "title": "Sessions flagged by the behavioral rules",
                "datasource": _DATASOURCE,
                "gridPos": {"h": 13, "w": 10, "x": 0, "y": 0},
                "targets": flagged_targets,
                "transformations": [
                    {"id": "merge", "options": {}},
                    {
                        "id": "organize",
                        "options": {
                            "excludeByName": {"Time": True},
                            "indexByName": {"rule": 0, "session": 1},
                            "includeByName": {"rule": True, "session": True},
                        },
                    },
                    {"id": "sortBy", "options": {"sort": [{"field": "rule"}]}},
                ],
            },
            {
                "id": 2,
                "type": "bargauge",
                "title": "Model call to command cycles per session (fires at 2.5)",
                "datasource": _DATASOURCE,
                "gridPos": {"h": 13, "w": 14, "x": 10, "y": 0},
                "targets": [
                    {
                        "refId": "A",
                        "datasource": _DATASOURCE,
                        "expr": _interleave_cycles(),
                        "queryType": "instant",
                        "legendFormat": "{{session}}",
                        "editorMode": "code",
                    }
                ],
                "options": {
                    "orientation": "horizontal",
                    "displayMode": "basic",
                    # An instant query returns one row per session; show each row.
                    "reduceOptions": {"values": True, "calcs": ["lastNotNull"], "limit": 6},
                },
                "transformations": [
                    {"id": "sortBy", "options": {"sort": [{"field": "Value #A", "desc": True}]}}
                ],
                "fieldConfig": {
                    "defaults": {
                        "min": 0,
                        "max": 5,
                        "decimals": 2,
                        "color": {"mode": "thresholds"},
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {"color": "green", "value": None},
                                {"color": "red", "value": 2.5},
                            ],
                        },
                    }
                },
            },
            {
                "id": 3,
                "type": "logs",
                "title": "s-loop-a: an agent loop (attack fixture)",
                "datasource": _DATASOURCE,
                "gridPos": {"h": 9, "w": 12, "x": 0, "y": 13},
                "targets": [
                    {"refId": "A", "datasource": _DATASOURCE, "expr": _session_logs("s-loop-a")}
                ],
                "options": {"showTime": True, "sortOrder": "Ascending", "wrapLogMessage": True},
            },
            {
                "id": 4,
                "type": "logs",
                "title": "s-retry-backoff: a backup job the LogQL retry rule flags by mistake",
                "datasource": _DATASOURCE,
                "gridPos": {"h": 9, "w": 12, "x": 12, "y": 13},
                "targets": [
                    {
                        "refId": "A",
                        "datasource": _DATASOURCE,
                        "expr": _session_logs("s-retry-backoff"),
                    }
                ],
                "options": {"showTime": True, "sortOrder": "Ascending", "wrapLogMessage": True},
            },
        ],
    }


def render_dashboard() -> str:
    return json.dumps(dashboard(), indent=2) + "\n"
